name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build:
    needs: setup
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
        include:
          - os: macos-13
            binary: libtes3_lua.dylib
            archive: macos-13-x86_64.zip
          - os: ubuntu-latest
            binary:  libtes3_lua.so
            archive: ubuntu-latest.zip
          - os: windows-latest
            binary: tes3_lua.dll
            archive: windows-latest.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: build
        run: cargo build --release

      - name: compress
        run: 7z a -tzip ${{matrix.archive}} ./target/release/${{matrix.binary}}

      - name: upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ matrix.archive }}
